# URI completa de conexión a MongoDB Atlas
mongodb.uri=mongodb+srv://mpartor0311_db_user:m4nu3l123456@cluster0.y1noj1v.mongodb.net/


# Nombre de la base de datos que quieres usar
mongodb.database=basededatosmanue
